//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:05:01 AM CEST 
//


package com.xml.booking.backendmain.ws_classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="users" type="{http://booking.xml.com/backendmain/ws-classes}userXML" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="catalogs" type="{http://booking.xml.com/backendmain/ws-classes}catalogXML" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="accommodations" type="{http://booking.xml.com/backendmain/ws-classes}accommodationXML" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reservations" type="{http://booking.xml.com/backendmain/ws-classes}reservationXML" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="messages" type="{http://booking.xml.com/backendmain/ws-classes}messageXML" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "users",
    "catalogs",
    "accommodations",
    "reservations",
    "messages"
})
@XmlRootElement(name = "getDBResponse")
public class GetDBResponse {

    protected List<UserXML> users;
    protected List<CatalogXML> catalogs;
    protected List<AccommodationXML> accommodations;
    protected List<ReservationXML> reservations;
    protected List<MessageXML> messages;

    /**
     * Gets the value of the users property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the users property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserXML }
     * 
     * 
     */
    public List<UserXML> getUsers() {
        if (users == null) {
            users = new ArrayList<UserXML>();
        }
        return this.users;
    }

    /**
     * Gets the value of the catalogs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catalogs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatalogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CatalogXML }
     * 
     * 
     */
    public List<CatalogXML> getCatalogs() {
        if (catalogs == null) {
            catalogs = new ArrayList<CatalogXML>();
        }
        return this.catalogs;
    }

    /**
     * Gets the value of the accommodations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accommodations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccommodations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccommodationXML }
     * 
     * 
     */
    public List<AccommodationXML> getAccommodations() {
        if (accommodations == null) {
            accommodations = new ArrayList<AccommodationXML>();
        }
        return this.accommodations;
    }

    /**
     * Gets the value of the reservations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reservations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReservations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationXML }
     * 
     * 
     */
    public List<ReservationXML> getReservations() {
        if (reservations == null) {
            reservations = new ArrayList<ReservationXML>();
        }
        return this.reservations;
    }

    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageXML }
     * 
     * 
     */
    public List<MessageXML> getMessages() {
        if (messages == null) {
            messages = new ArrayList<MessageXML>();
        }
        return this.messages;
    }

}
