//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 05:36:17 AM CEST 
//


package com.xml.booking.backendmain.ws_classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.booking.backendmain.ws_classes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.booking.backendmain.ws_classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddReservationsResponse }
     * 
     */
    public AddReservationsResponse createAddReservationsResponse() {
        return new AddReservationsResponse();
    }

    /**
     * Create an instance of {@link ReservationXML }
     * 
     */
    public ReservationXML createReservationXML() {
        return new ReservationXML();
    }

    /**
     * Create an instance of {@link DeleteReservationResponse }
     * 
     */
    public DeleteReservationResponse createDeleteReservationResponse() {
        return new DeleteReservationResponse();
    }

    /**
     * Create an instance of {@link AddAccommodationRequest }
     * 
     */
    public AddAccommodationRequest createAddAccommodationRequest() {
        return new AddAccommodationRequest();
    }

    /**
     * Create an instance of {@link AccommodationXML }
     * 
     */
    public AccommodationXML createAccommodationXML() {
        return new AccommodationXML();
    }

    /**
     * Create an instance of {@link GetDBRequest }
     * 
     */
    public GetDBRequest createGetDBRequest() {
        return new GetDBRequest();
    }

    /**
     * Create an instance of {@link DeleteReservationRequest }
     * 
     */
    public DeleteReservationRequest createDeleteReservationRequest() {
        return new DeleteReservationRequest();
    }

    /**
     * Create an instance of {@link AddMessageResponse }
     * 
     */
    public AddMessageResponse createAddMessageResponse() {
        return new AddMessageResponse();
    }

    /**
     * Create an instance of {@link MessageXML }
     * 
     */
    public MessageXML createMessageXML() {
        return new MessageXML();
    }

    /**
     * Create an instance of {@link AddAccommodationResponse }
     * 
     */
    public AddAccommodationResponse createAddAccommodationResponse() {
        return new AddAccommodationResponse();
    }

    /**
     * Create an instance of {@link LogInResponse }
     * 
     */
    public LogInResponse createLogInResponse() {
        return new LogInResponse();
    }

    /**
     * Create an instance of {@link UserXML }
     * 
     */
    public UserXML createUserXML() {
        return new UserXML();
    }

    /**
     * Create an instance of {@link AddMessageRequest }
     * 
     */
    public AddMessageRequest createAddMessageRequest() {
        return new AddMessageRequest();
    }

    /**
     * Create an instance of {@link LogInRequest }
     * 
     */
    public LogInRequest createLogInRequest() {
        return new LogInRequest();
    }

    /**
     * Create an instance of {@link ConfirmReservationRequest }
     * 
     */
    public ConfirmReservationRequest createConfirmReservationRequest() {
        return new ConfirmReservationRequest();
    }

    /**
     * Create an instance of {@link GetDBResponse }
     * 
     */
    public GetDBResponse createGetDBResponse() {
        return new GetDBResponse();
    }

    /**
     * Create an instance of {@link CatalogXML }
     * 
     */
    public CatalogXML createCatalogXML() {
        return new CatalogXML();
    }

    /**
     * Create an instance of {@link TestRequest }
     * 
     */
    public TestRequest createTestRequest() {
        return new TestRequest();
    }

    /**
     * Create an instance of {@link AddReservationsRequest }
     * 
     */
    public AddReservationsRequest createAddReservationsRequest() {
        return new AddReservationsRequest();
    }

    /**
     * Create an instance of {@link ConfirmReservationResponse }
     * 
     */
    public ConfirmReservationResponse createConfirmReservationResponse() {
        return new ConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

}
